### ISSUE TITLE
Mewnbase (Native)

### ISSUE THREAD

**Issue by ricoazzurro** [ptitSeb/box86-compatibility-list#473]
### Description

Mewnbase, v1.0.1, Linux x64, itch, Engine: LWJGL

Box64 with Dynarec v0.2.7 7dee075
Rock 5B, LFS, Kernel rk-6.1-rkr1-panthor-v6, Mesa 24.1.0, Gnome 46

- No sound.
- Log shows `Error loading needed lib libpipewire-0.3.so.0`
- Tried `BOX64_PREFER_EMULATED=1`

Error Log,
```bash
rico [ /opt/games/mewnbase ]$ ./box64-start.sh 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A55 Cortex-A76 with 8 Cores
Will use Hardware counter measured at 24.0 MHz emulating 768 MHz
Params database has 62 entries
Box64 with Dynarec v0.2.7 7dee075 built on Apr 14 2024 11:40:27
BOX64: Detected 48bits at least of address space
Counted 63 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/opt/rustc/bin/:/usr/local/bin/:/usr/bin/:/opt/ant/bin/:/opt/jdk/bin/:/opt/bin/
Looking for ./MewnBase
Rename process to "MewnBase"
Using native(wrapped) libdl.so.2
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated jre/lib/amd64/server/libjvm.so
libjvm detected, disable Dynarec BigBlock and enable Dynarec StrongMem
Using emulated /opt/games/mewnbase/jre/lib/amd64/libverify.so
Using emulated /opt/games/mewnbase/jre/lib/amd64/libjava.so
Using emulated /opt/games/mewnbase/jre/lib/amd64/libzip.so
MewnBase v1.0.1 | OS: Linux
MewnBase launch args: 
Using emulated /tmp/libgdxrico/ef811645/libgdx64.so
Using emulated /opt/games/mewnbase/jre/lib/amd64/libnio.so
Using emulated /opt/games/mewnbase/jre/lib/amd64/libnet.so
Using emulated /tmp/lwjgl_rico/3.3.2-snapshot/x64/liblwjgl.so
Using emulated /tmp/lwjgl_rico/3.3.2-snapshot/x64/libjemalloc.so
Using emulated /tmp/lwjgl_rico/3.3.2-snapshot/x64/libglfw.so
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libX11-xcb.so.1
Using emulated /tmp/lwjgl_rico/3.3.2-snapshot/x64/libopenal.so
Error loading needed lib libpipewire-0.3.so.0
Warning: Cannot dlopen("libpipewire-0.3.so.0"/0x7fff0d0cea00, 2)
Using native(wrapped) libpulse.so.0
[Lwjgl3Application] Couldn't initialize audio, disabling audio
java.lang.IllegalStateException: Core OpenAL functions could not be found. Make sure that the OpenAL library has been loaded correctly.
	at org.lwjgl.openal.AL.createCapabilities(AL.java:157)
	at org.lwjgl.openal.AL.createCapabilities(AL.java:124)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.<init>(OpenALLwjgl3Audio.java:105)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createAudio(Lwjgl3Application.java:419)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:147)
	at com.cairn4.moonbase.desktop.DesktopLauncher.main(DesktopLauncher.java:57)
Error initializing native libGLX.so.0 (last dlerror is libGLX.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libGLX.so.0
Warning: Cannot dlopen("libGLX.so.0"/0x7fff0c0560b6, 1)
Using native(wrapped) libGL.so.1
Using emulated /tmp/lwjgl_rico/3.3.2-snapshot/x64/liblwjgl_opengl.so
[MewnBase] MoonBase.coreFolder = data/
[MewnBase] SettingsLoader: validating settings file
[MewnBase] Vsync: true
[MewnBase] SettingsLoader: Writing settings to disk.
[MewnBase] Using HD mode: true
[MewnBase] Compiling shaders...
[MewnBase] Found no save files with errors.
[MewnBase] -----------------
[MewnBase] SaveFixer: Testing entity fix for 0 saves.
Using emulated /tmp/steamworks4j/1.8.0/libsteam_api.so
Using emulated /tmp/steamworks4j/1.8.0/libsteamworks4j.so
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
  Steam API initialized: false
  Steam client active: false
[MewnBase] Linux
[MewnBase] System Language: en_US
[MewnBase] Setting language to: en
[MewnBase] Locale: en
[MewnBase] Showing menu: MainMenu
[MewnBase] prev screen now : Splash
[MewnBase] finished showing main menu
[MewnBase] Showing menu: MoreMenu
[MewnBase] Showing menu: SettingsPopup
[MewnBase] SettingsLoader: Writing settings to disk.
[MewnBase] Back
[MewnBase] Back
[MewnBase] Showing menu: NewGameScreen
[MewnBase] Showing menu: CreatePlayerScreen
[MewnBase] Showing menu: MissionBriefing
[MewnBase] CreatureManager: Reading creature data
[MewnBase] Loading assets for crab
[MewnBase] Loading assets for firecrab
[MewnBase] Loading assets for slug
[MewnBase] Loading assets for fireslug
[MewnBase] prev screen now : FrontendScreen
[MewnBase] Done loading game assets.

----------

[ShaderLoader] Compiling "screenspace/heat"...
[MewnBase] ItemFactory: 116 items loaded.
Using emulated /tmp/libgdxrico/75bc14d6/libgdx-box2d64.so
[MewnBase] DayCycle: Period is now: day
[ShaderLoader] Compiling "screenspace/convolve-1d" w/ (#define LENGTH 3)...
[ShaderLoader] Compiling "screenspace/convolve-1d" w/ (#define LENGTH 3)...
[ShaderLoader] Compiling "screenspace/convolve-1d" w/ (#define LENGTH 5)...
[ShaderLoader] Compiling "screenspace/convolve-1d" w/ (#define LENGTH 5)...
[ShaderLoader] Compiling "screenspace/threshold"...
[ShaderLoader] Compiling "screenspace/combine"...
[MewnBase] change weather :clear
[MewnBase] TechManager: techTree.json does not exist
[MewnBase] TechManager: Loaded 20 tech upgrades
[MewnBase] World: Generating random seed
[MewnBase] TerrainGen: Setting terrain seed to 4925
[MewnBase] TerrainGen: Setting terrain wet seed to 4926
[MewnBase] FeatureTileFactory: Loading...
[MewnBase] FeatureTileFactory loaded 1 items
[MoonBase] ItemDropperFactory: Loading Item Droppers
[MewnBase] ChunkLoader: Creating new chunk: 50,51
[MewnBase] ChunkLoader: Creating new chunk: 51,51
[MewnBase] ChunkLoader: Creating new chunk: 51,50
[MewnBase] ChunkLoader: Creating new chunk: 51,49
[MewnBase] ChunkLoader: Creating new chunk: 50,49
[MewnBase] ChunkLoader: Creating new chunk: 49,49
[MewnBase] ChunkLoader: Creating new chunk: 49,50
[MewnBase] ChunkLoader: Creating new chunk: 49,51
[MewnBase] Removing tile from landing site: ItemDropper
[MewnBase] Removing tile from landing site: ItemDropper
[MewnBase] Removing tile from landing site: ItemDropper
[MewnBase] Removing tile from landing site: ItemDropper
[MewnBase] Removing tile from landing site: ItemDropper
[MewnBase] Removing tile from landing site: ItemDropper
[MewnBase] Setting dayCycle to : defaultDay
[MewnBase] DayCycle: Period is now: day
[MewnBase] creating resource bar
[MewnBase] creating resource bar
[MewnBase] creating resource bar
[MewnBase] creating resource bar
[MewnBase] DialogController: Reading data
[MewnBase] DialogController: List size: 0
[MewnBase] prev screen now : LoadingScreen
[MoonBase] Player: Playing exit lander anim
[MewnBase] GameLoader: Loading game from folder Rico
[MewnBase] GameLoader: can't find save data for folder Rico
[MewnBase] path1destfolder doesn't exist, creating
[MewnBase] GameLoader: Writing gameSaveData: Rico
[MoonBase] Player: changed chunks!: 50, 50
[MewnBase] adding crate radar node
[MewnBase] adding crate radar node
[MewnBase] ----------------
Hit a ui thing! Button
[MewnBase] ----------------
Hit a ui thing! Button
[MoonBase] Player: changed chunks!: 50, 49
[MewnBase] ChunkLoader: Creating new chunk: 51,48
[MewnBase] ChunkLoader: Creating new chunk: 50,48
[MewnBase] ChunkLoader: Creating new chunk: 49,48
[MewnBase] ItemDropper: Dropping loot action
[MewnBase] RegrowthManager: adding new respawnable - blueshroom-sprout
[MewnBase] Updating Bases!
[MewnBase] collected into existing stacks: 0
[MewnBase] newStack size remaining: 1
[MewnBase] new stack has 1
[MewnBase] Added blueshroom (1) to player inventory
[MewnBase] World: pauseSimulation -> true
[MewnBase] SettingsLoader: Writing settings to disk.
[MewnBase] Back
[MewnBase] Showing menu: MainMenu
[MewnBase] GameScreen:hide
[MewnBase] prev screen now : GameScreen
[MewnBase] finished showing main menu
Using emulated /opt/games/mewnbase/jre/lib/amd64/libawt.so
Using emulated /opt/games/mewnbase/jre/lib/amd64/libawt_xawt.so
Using native(wrapped) libXtst.so.6
Using emulated /opt/games/mewnbase/jre/lib/amd64/libfontmanager.so
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libgtk-x11-2.0.so.0
Using native(wrapped) libgdk-x11-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libgthread-2.0.so.0
Error loading needed lib libgnomevfs-2.so.0
Warning: Cannot dlopen("libgnomevfs-2.so.0"/0x7fff1304dc90, 1)
Error loading needed lib libgnomevfs-2.so
Warning: Cannot dlopen("libgnomevfs-2.so"/0x7fff1304dca3, 1)
can not load libgnomevfs-2.so
1956| Strange SIGSEGV with Access error on 0xffff22819c3c for 0x60010f00 mapped, db=0xffff2c07caf8, prot=0x3 (old_addr=(nil), Lock=0x0)
PlatformAdapter:dispose()
true
[MewnBase] SteamAPI.shutdown
./box64-start.sh: line 17:  1936 Segmentation fault      (core dumped) box64 ./"MewnBase
```

### Tested on

- Box64 with Dynarec v0.2.7 7dee075
- Radxa Rock 5B, (RK3588, Cortex-A76+Cortex-A55, Mali-G610)
- LFS r12.1-30
BSP Kernel 6.1.43+ (rk-6.1-rkr1-panthor-v6 6bd0bc6)
Mesa 24.1.0-devel (git-35831dded5)
Gnome 46
- 1080p, Default game settings

### Status
**Previous behavior:** 

Not working. Might be the panfork issue.
https://github.com/ptitSeb/box86-compatibility-list/issues/411

**Current behavior:**

The game can be played but no sound.

### Screenshots

![Mewnbase-1](https://github.com/ptitSeb/box86-compatibility-list/assets/108268247/87724398-74bf-4dde-8df8-ef548194f36d)
![Mewnbase-2](https://github.com/ptitSeb/box86-compatibility-list/assets/108268247/b540ffd0-8864-451e-9879-ac08a3181553)
![Mewnbase-3](https://github.com/ptitSeb/box86-compatibility-list/assets/108268247/724c0a74-8624-4195-ab44-170a8571748c)

### OpenGL

OpenGL 2.1

### Additional Information

https://cairn4.com/
https://cairn4.itch.io/mewnbase
https://store.steampowered.com/app/743130/MewnBase/
https://www.pcgamingwiki.com/wiki/MewnBase

**Comment by ptitSeb** [comment]
pipewire is indeed, not wrapped. May need to be added in medium-term todo list tho, as it's more and more default on every distro.

**Comment by ricoazzurro** [comment]
Yahooo, in todo list.
SDL3 also prefers pipewire now.
